name: C++ Tests

on:
    pull_request:
        branches: [main] # Adjust this to match your main branch name

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        container: ubuntu:23.04 # or another recent version

        steps:
            - name: Install newer GCC
              run: |
                  sudo apt update
                  sudo apt install -y g++-16
            - name: Set GCC 16 as default
              run: |
                  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-16 100
                  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-16 100

            - uses: actions/checkout@v4.2.2

            - name: Setup cmake
              uses: jwlawson/actions-setup-cmake@v2
              with:
                  cmake-version: "3.14"

            - name: Configure CMake
              run: cmake -S . -B build -DBUILD_TESTS=ON

            - name: Build
              run: cmake --build build

            - name: Run Tests
              run: ./build/tests/unit_tests
