name: C++ Tests

on:
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.2

            - name: Setup cmake
              uses: jwlawson/actions-setup-cmake@v2
              with:
                  cmake-version: "3.20"

            - name: Build Project
              run: |
                  mkdir build-tests
                  cd build-tests
                  cmake -DBUILD_TESTS=ON -Wno-dev ..
                  make

            - name: Run C++ Unit Tests
              run: |
                  cd build-tests
                  ctest --rerun-failed --output-on-failure

            - name: Clean Up
              run: |
                  rm -rf build-tests
                  echo "Cleaned up build directory"
