name: C++ Tests

on:
  pull_request:
    branches: [main]  # Adjust this to match your main branch name

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up CMake
      uses: actions/setup-cmake@v1
      
    - name: Configure CMake
      run: cmake -S . -B build -DBUILD_TESTS=ON
    
    - name: Build
      run: cmake --build build
    
    - name: Run Tests
      run: ./build/tests/unit_tests
